/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingredients */
        get: operations["list_ingredients_api_v1_ingredients_get"];
        put?: never;
        /** Create Ingredient Route */
        post: operations["create_ingredient_route_api_v1_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredient */
        get: operations["get_ingredient_api_v1_ingredients__ingredient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ingredient Route */
        patch: operations["update_ingredient_route_api_v1_ingredients__ingredient_id__patch"];
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_api_v1_recipes_get"];
        put?: never;
        /** Create Recipe Route */
        post: operations["create_recipe_route_api_v1_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Recipe Route */
        patch: operations["update_recipe_route_api_v1_recipes__recipe_id__patch"];
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        /** Create Location Route */
        post: operations["create_location_route_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location */
        get: operations["get_location_api_v1_locations__location_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Location Route */
        patch: operations["update_location_route_api_v1_locations__location_id__patch"];
        trace?: never;
    };
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_v1_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Movement */
        post: operations["create_movement_api_v1_movements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reversals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Reversal */
        post: operations["create_reversal_api_v1_reversals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Visit */
        post: operations["create_visit_api_v1_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit */
        get: operations["get_visit_api_v1_visits__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_v1_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_api_v1_entries__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_v1_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BakeCountItem */
        BakeCountItem: {
            /** Size Id */
            size_id: number;
            /** Count */
            count: number;
        };
        /** BatchCreate */
        BatchCreate: {
            /** Recipe Id */
            recipe_id: number;
            /**
             * Baked
             * Format: date
             */
            baked: string;
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Counts */
            counts: components["schemas"]["BakeCountItem"][];
        };
        /** BatchRead */
        BatchRead: {
            /** Id */
            id: number;
            /** Recipe Id */
            recipe_id: number;
            /** Entry Id */
            entry_id: number;
            /**
             * Baked
             * Format: date
             */
            baked: string;
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Total Cost Cents */
            total_cost_cents: number;
            /** Sizes */
            sizes: components["schemas"]["BatchSizeRead"][];
        };
        /** BatchSizeRead */
        BatchSizeRead: {
            /** Size Id */
            size_id: number;
            /** Count Made */
            count_made: number;
            /** Unit Cost Cents */
            unit_cost_cents: number;
        };
        /** BatchStockRead */
        BatchStockRead: {
            /** Batch Id */
            batch_id: number;
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Quantity */
            quantity: number;
            /**
             * State
             * @enum {string}
             */
            state: "expired" | "expiring_soon" | "ok";
        };
        /** EntryRead */
        EntryRead: {
            /** Entry Id */
            entry_id: number;
            /** Kind */
            kind: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Voided */
            voided: boolean;
            /** Location Id */
            location_id: number | null;
            /** Revenue Cents */
            revenue_cents: number | null;
            /** Profit Cents */
            profit_cents: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IngredientCreate */
        IngredientCreate: {
            /** Name */
            name: string;
            /** Unit Label */
            unit_label: string;
            /** Current Price Cents */
            current_price_cents: number;
        };
        /** IngredientRead */
        IngredientRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Unit Label */
            unit_label: string;
            /** Current Price Cents */
            current_price_cents: number;
            /** Active */
            active: boolean;
        };
        /** IngredientUpdate */
        IngredientUpdate: {
            /** Name */
            name?: string | null;
            /** Unit Label */
            unit_label?: string | null;
            /** Current Price Cents */
            current_price_cents?: number | null;
            /** Active */
            active?: boolean | null;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "stand" | "market";
        };
        /**
         * LocationPatch
         * @description No `kind` field: kind is immutable, so a payload naming it is an unknown key (422).
         */
        LocationPatch: {
            /** Name */
            name?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** LocationRead */
        LocationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Active */
            active: boolean;
        };
        /**
         * LoginRequest
         * @description `POST /api/v1/session` body: the shared password, nothing else.
         */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** MarketRowIn */
        MarketRowIn: {
            /** Size Id */
            size_id: number;
            /** Taken */
            taken: number;
            /** Returned */
            returned: number;
            /** Tossed */
            tossed: number;
        };
        /** MarketVisitCreate */
        MarketVisitCreate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "market";
            /** Location Id */
            location_id: number;
            /** Rows */
            rows?: components["schemas"]["MarketRowIn"][];
            /** Revenue Cents */
            revenue_cents: number;
            /** Fee Cents */
            fee_cents: number;
        };
        /** MovementCreate */
        MovementCreate: {
            /** From Location Id */
            from_location_id: number;
            /** To Location Id */
            to_location_id: number;
            /** Size Id */
            size_id: number;
            /** Quantity */
            quantity: number;
        };
        /** ProfitRead */
        ProfitRead: {
            /** Sold Cost Cents */
            sold_cost_cents: number;
            /** Waste Cost Cents */
            waste_cost_cents: number;
            /** Sampled Cost Cents */
            sampled_cost_cents: number;
            /** Profit Cents */
            profit_cents: number;
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days: number;
            /** Lines */
            lines?: components["schemas"]["RecipeLineInput"][];
            /** Sizes */
            sizes: components["schemas"]["SizeCreate"][];
        };
        /** RecipeLineInput */
        RecipeLineInput: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Quantity */
            quantity: number;
        };
        /** RecipeLineRead */
        RecipeLineRead: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Quantity */
            quantity: number;
        };
        /** RecipePatch */
        RecipePatch: {
            /** Name */
            name?: string | null;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
            /** Lines */
            lines?: components["schemas"]["RecipeLineInput"][] | null;
            /** Sizes */
            sizes?: components["schemas"]["SizePatchItem"][] | null;
        };
        /** RecipeRead */
        RecipeRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days: number;
            /** Lines */
            lines: components["schemas"]["RecipeLineRead"][];
            /** Sizes */
            sizes: components["schemas"]["SizeRead"][];
        };
        /** ReversalCreate */
        ReversalCreate: {
            /** Entry Id */
            entry_id: number;
        };
        /** ReversalRead */
        ReversalRead: {
            /** Entry Id */
            entry_id: number;
            /** Reverses Entry Id */
            reverses_entry_id: number;
        };
        /** SizeCreate */
        SizeCreate: {
            /** Name */
            name: string;
            /** Portion Weight G */
            portion_weight_g: number;
            /** Price Cents */
            price_cents: number;
            /** Typical Yield Count */
            typical_yield_count: number;
        };
        /**
         * SizePatchItem
         * @description One `sizes` patch item: `id` present updates that size, absent creates one.
         *
         *     `id` is typed `int | SkipJsonSchema[None]` rather than plain
         *     `int | None`: Pydantic renders a bare `int | None` as `anyOf:
         *     [{type: integer}, {type: null}]`, which tells an OpenAPI client
         *     that an explicit `null` is a valid value. It is not -- the
         *     `_reject_explicit_null_id` validator below rejects `{"id": null}`
         *     at the wire -- so the generated schema should read as a plain
         *     optional integer (present or absent, never `null`).
         *     `SkipJsonSchema[None]` drops the `null` branch from the *schema*
         *     only; Python still sees `None` when the key is omitted, and the
         *     validator below still runs on every payload, `null` included.
         */
        SizePatchItem: {
            /** Id */
            id?: number;
            /** Name */
            name?: string | null;
            /** Portion Weight G */
            portion_weight_g?: number | null;
            /** Price Cents */
            price_cents?: number | null;
            /** Typical Yield Count */
            typical_yield_count?: number | null;
        };
        /** SizeRead */
        SizeRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Portion Weight G */
            portion_weight_g: number;
            /** Price Cents */
            price_cents: number;
            /** Typical Yield Count */
            typical_yield_count: number;
            /** Estimated Unit Cost Cents */
            estimated_unit_cost_cents: number;
        };
        /** SizeStockRead */
        SizeStockRead: {
            /** Size Id */
            size_id: number;
            /** Size Name */
            size_name: string;
            /** Recipe Id */
            recipe_id: number;
            /** Recipe Name */
            recipe_name: string;
            /** Quantity */
            quantity: number;
            /** Batches */
            batches: components["schemas"]["BatchStockRead"][];
        };
        /** StandRowIn */
        StandRowIn: {
            /** Size Id */
            size_id: number;
            /** Counted */
            counted: number;
            /** Tossed */
            tossed: number;
            /** Pulled */
            pulled: number;
            /** Added */
            added: number;
        };
        /** StandVisitCreate */
        StandVisitCreate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stand";
            /** Location Id */
            location_id: number;
            /** Rows */
            rows?: components["schemas"]["StandRowIn"][];
            /** Revenue Cents */
            revenue_cents: number;
        };
        /** StockRead */
        StockRead: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Sizes */
            sizes: components["schemas"]["SizeStockRead"][];
        };
        /** VisitRead */
        VisitRead: {
            /** Entry Id */
            entry_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "stand" | "market";
            /** Location Id */
            location_id: number;
            /** Revenue Cents */
            revenue_cents: number;
            /** Fee Cents */
            fee_cents: number;
            /** Expected Revenue Cents */
            expected_revenue_cents: number;
            /** Difference Cents */
            difference_cents: number;
            profit: components["schemas"]["ProfitRead"] | null;
        };
        /**
         * Problem
         * @description An RFC 9457 Problem Details document; extra keys are extension members.
         */
        Problem: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_ingredients_api_v1_ingredients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_ingredient_route_api_v1_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_ingredient_api_v1_ingredients__ingredient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_ingredient_route_api_v1_ingredients__ingredient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_recipes_api_v1_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_recipe_route_api_v1_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_recipe_route_api_v1_recipes__recipe_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_location_route_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_location_api_v1_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_location_route_api_v1_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_batch_api_v1_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_batch_api_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_movement_api_v1_movements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_reversal_api_v1_reversals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReversalRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_visit_api_v1_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandVisitCreate"] | components["schemas"]["MarketVisitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_visit_api_v1_visits__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_entries_api_v1_entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_entry_api_v1_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_stock_api_v1_stock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
